version: '3.8'

services:
  # --- Databases ---
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: proctoring_db
      MYSQL_USER: proctor_user
      MYSQL_PASSWORD: proctor_password
      TZ: Asia/Almaty
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - proctor_net

  redis:
    image: redis:alpine
    environment:
      TZ: Asia/Almaty
    networks:
      - proctor_net

  # --- Object Storage ---
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
      TZ: Asia/Almaty
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI
    volumes:
      - minio_data:/data
    networks:
      - proctor_net

  # Создает бакеты автоматически при старте
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      TZ: Asia/Almaty
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/exam-recordings;
      /usr/bin/mc policy set download myminio/exam-recordings;
      exit 0;
      "
    networks:
      - proctor_net

  # --- App ---
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: mysql+pymysql://proctor_user:proctor_password@db/proctoring_db
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: exam-recordings
      MINIO_PUBLIC_URL: http://localhost:9000
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TZ: Asia/Almaty
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - proctor_net

  # Frontend (в Dev режиме)
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://backend:8000
      API_URL: http://backend:8000
      TZ: Asia/Almaty
    networks:
      - proctor_net

volumes:
  mysql_data:
  minio_data:

networks:
  proctor_net:
    driver: bridge
